===== Verwaltung

In dem Untermenü Verwaltung finden sich weitere die wie folgt sind :

'''
[[configuration]]
- Konfiguration :  
Unter diesem Menü findet man verschiedene Einstellungen die mann für die DomoPro Software ändern kann.
include::Konfiguration.asciidoc[]

'''
[[user]]
- Benutzer : 
Unter diesem Menü kann mann neue Benutzer hinzufügen oder auch vorhandene enfernen
include::Benutzer.asciidoc[]

'''
[[backup]]
- Sicherungskopie : 
Unter diesm Menü werden Sicherungskopien angelegt und wieder hergestellt.
include::Sicherungskopie.asciidoc[]

'''
[[update]]
- Update Center : 
Im Update Center werden alle zur verfügung stehenden Updates angeboten.
include::updatecenter.asciidoc[]

'''
[[jeeNetwork]]
- DomoPro Netzwerk : 
Das Menü ist nur im Expertenmodus zur Verfügung
Seite, die ermöglicht, mehrere DomoPro in der Weise zu verbinden, maitre / Sklave. Diese Möglichkeit ermöglicht zum Beispiel, den Zwave, den Rfxcom, den EnOcean oder GSM auf anderem mini Raspberry piou DomoPro zu deporter. Sie werden auch ab dieser Seite können, einen Status Ihrer DomoPro Sklaven zu haben, ihren Log, die Mettres pro Tag zu befragen, sie anzuhalten, … 
include::JeedoNetzwerk.asciidoc[]

'''
[[cron]]
- Task-Engine : 
Das Task-Engine Menü ist nur im Expertenmodus zur Verfügung. Es informiert über alle DomoPro Anwendungsaufgaben die auf dem Server ausgeführt werden. 
include::Task-Engine.asciidoc[]

'''
[[security]]
- Sicherheit : 
Unter dem Menü Sicherheit wird um das System geschützt . Primäre DomoPro "Anti-Piraterie" Konfiguration eingestellt. Es ist nur im Expertenmodus zur Verfügung. Dies ist eine IP-Adresse Verbot System, wenn einer sich mehrmals ohne Erfolg versucht, sich mit DomoPro zu verbinden.
include::sicherheit.asciidoc[]

'''
[[log]]
- Logs : 
Im Log Menü werden die verschiedenen Log dateien die DomoPro anlegt untersucht werden. Das Menü ist nur im Expertenmodus zur Verfügung
include::logs.asciidoc[]

'''
[[info_system]]
- System Information : 
System Informationen über die Hardware sind in diesem Menü zu sehen. Das Menü ist nur im Expertenmodus zur Verfügung
include::SystemInformation.asciidoc[]

'''
[[erw_anpas]]
- Erweiterte Anpassung : 
Erweiterte Anpassungen können hier erfolgen. Das Menü ist nur im Expertenmodus zur Verfügung
include::Erweiterte_Anpassung.asciidoc[]
